name: Test image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: MACROARM64
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Refresh image
        run: |
          docker build -t esp32-micropython-server .
          docker stop esp32-micropython-server || true
          docker run -itd --rm --device /dev/ttyUSB0 -p 8955:8955 --name esp32-micropython-server esp32-micropython-server 